-- MySQL Script generated by MySQL Workbench
-- 12/15/14 10:12:17
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema trackdb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema trackdb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `trackdb` DEFAULT CHARACTER SET utf8 ;
USE `trackdb` ;

-- -----------------------------------------------------
-- Table `trackdb`.`uwikiz`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `trackdb`.`uwikiz` ;

CREATE TABLE IF NOT EXISTS `trackdb`.`uwikiz` (
  `uwiki_id` INT NOT NULL,
  `uwiki_version` VARCHAR(45) NULL,
  `uwiki_text` VARCHAR(225) NULL,
  `uwikiz_date_created` DATE NULL,
  `uwiki_edited_user_id` INT NULL,
  `uwiki_text_length` INT NULL,
  PRIMARY KEY (`uwiki_id`),
  INDEX `uwikizuserfk_idx` (`uwiki_edited_user_id` ASC),
  CONSTRAINT `uwikizuserfk`
    FOREIGN KEY (`uwiki_edited_user_id`)
    REFERENCES `trackdb`.`user` (`userid`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `trackdb`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `trackdb`.`user` ;

CREATE TABLE IF NOT EXISTS `trackdb`.`user` (
  `userid` INT NOT NULL,
  `user_name` VARCHAR(128) NOT NULL,
  `user_pass` VARCHAR(128) NOT NULL,
  `user_status` VARCHAR(128) NULL,
  `user_email` VARCHAR(128) NULL,
  `user_date_created` DATE NULL,
  `user_uwiki_id` INT NULL,
  PRIMARY KEY (`userid`),
  UNIQUE INDEX `usernameUniqueIndex` (`user_name` ASC),
  INDEX `useruwikizfk_idx` (`user_uwiki_id` ASC),
  CONSTRAINT `useruwikizfk`
    FOREIGN KEY (`user_uwiki_id`)
    REFERENCES `trackdb`.`uwikiz` (`uwiki_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `trackdb`.`qwikiz`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `trackdb`.`qwikiz` ;

CREATE TABLE IF NOT EXISTS `trackdb`.`qwikiz` (
  `qwiki_id` INT NOT NULL,
  `qwiki_version` INT NULL,
  `qwiki_text` VARCHAR(225) NULL,
  `qwiki_date_created` DATE NULL,
  `qwiki_edited_user_id` INT NULL,
  `qwiki_text_length` INT NULL,
  `qwiki_date_deadline` DATE NULL,
  `qwiki_importance` VARCHAR(222) NULL,
  `qwiki_complete` INT(4) NULL,
  `qwiki_privacy` VARCHAR(200) NULL,
  PRIMARY KEY (`qwiki_id`),
  INDEX `qwikiuserfk_idx` (`qwiki_edited_user_id` ASC),
  CONSTRAINT `qwikiuserfk`
    FOREIGN KEY (`qwiki_edited_user_id`)
    REFERENCES `trackdb`.`user` (`userid`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `trackdb`.`questz`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `trackdb`.`questz` ;

CREATE TABLE IF NOT EXISTS `trackdb`.`questz` (
  `quest_id` INT NOT NULL AUTO_INCREMENT,
  `quest_name` VARCHAR(128) NULL,
  `quest_date_created` DATE NULL,
  `quest_creator_lastedit` DATE NULL,
  `quest_qwiki_id` INT NULL,
  PRIMARY KEY (`quest_id`),
  INDEX `questzqwikizfk_idx` (`quest_qwiki_id` ASC),
  CONSTRAINT `questzqwikizfk`
    FOREIGN KEY (`quest_qwiki_id`)
    REFERENCES `trackdb`.`qwikiz` (`qwiki_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `trackdb`.`execz`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `trackdb`.`execz` ;

CREATE TABLE IF NOT EXISTS `trackdb`.`execz` (
  `exec_quest_id` INT NOT NULL,
  `exec_user_id` INT NULL,
  `execactual` INT(2) NULL,
  PRIMARY KEY (`exec_quest_id`),
  INDEX `execzuserfk_idx` (`exec_user_id` ASC),
  CONSTRAINT `execzuserfk`
    FOREIGN KEY (`exec_user_id`)
    REFERENCES `trackdb`.`user` (`userid`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `execzquestzfk`
    FOREIGN KEY (`exec_quest_id`)
    REFERENCES `trackdb`.`questz` (`quest_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `trackdb`.`userprofile`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `trackdb`.`userprofile` ;

CREATE TABLE IF NOT EXISTS `trackdb`.`userprofile` (
  `userid` INT NOT NULL,
  `lastname` VARCHAR(128) NULL DEFAULT NULL,
  `firstname` VARCHAR(128) NULL DEFAULT NULL,
  PRIMARY KEY (`userid`),
  CONSTRAINT `userProfileUserFK`
    FOREIGN KEY (`userid`)
    REFERENCES `trackdb`.`user` (`userid`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `trackdb`.`user`
-- -----------------------------------------------------
START TRANSACTION;
USE `trackdb`;
INSERT INTO `trackdb`.`user` (`userid`, `user_name`, `user_pass`, `user_status`, `user_email`, `user_date_created`, `user_uwiki_id`) VALUES (1, 'admin', 'admin', 'admin', 'admin@yandex.ru', '10.12.2014', 1);

COMMIT;

